spring.application.name=booking
spring.data.mongodb.uri=mongodb+srv://pafmongodb_db_user:BhA6GLc4vFUKdIQ6@cluster0.rm0kl5u.mongodb.net/smartcampus?retryWrites=true&w=majority&authSource=admin
server.port=8082

logging.level.com.smartcampus.booking=DEBUG
spring.mvc.cors.allowed-origins=http://localhost:5173,http://localhost:5174,http://localhost:5175

# Multipart/form-data configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB