wrapperVersion=3.3.4
distributionType=only-script
<<<<<<< HEAD
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.14/apache-maven-3.9.14-bin.zip
=======
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.9/apache-maven-3.9.9-bin.zip
>>>>>>> 3409d4892568add3080ba77dd736f8a4fcc24ef1
